---
name: Build Kernel vnkernelmod
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        path: kernel
    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"
    - name: ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: build-${{ steps.timestamp.outputs.timestamp }}
        restore-keys: |
          build-${{ steps.timestamp.outputs.timestamp }}
          build-
    - name: Build With Shell
      run: |
        bash kernel/build-cbl.sh
    - name: Upload zip package
      uses: actions/upload-artifact@master
      with:
        path: kernel/AnyKernel3
        name: Feisty
