---
name: Build Kernel Feisty
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        path: kernel
    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"
    - name: ccache
      uses: actions/cache@v1
      env:
        cache-name: ccache
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.timestamp.outputs.timestamp }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build With Shell
      run: |
        bash kernel/build-cbl.sh
    - name: Upload zip package
      uses: actions/upload-artifact@master
      with:
        path: kernel/AnyKernel3
        name: Feisty
