name: Build Kernel Feisty
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        path: kernel
    - name: Build With Shell
      run: |
        bash kernel/build-cbl.sh
    - name : Upload zip package
      uses: actions/upload-artifact@master
      with:
        path: kernel/AnyKernel3
        name: Feisty_${{ env.github_ref }}_r${{ env.github.run_id }}
